name = "nceahelpworker"
type = "javascript"
main = "./src/server.js"
compatibility_date="2022-02-26"

account_id = "4ed1f8e12cda519236361f09dd8956cf"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
