name = "compserverhelper"
main = "./src/server.ts"
compatibility_date="2025-06-27"

account_id= "4ed1f8e12cda519236361f09dd8956cf"
send_metrics = true
minify = true

routes = [
  { pattern = "vuwtechbot.workers.deez.ing", custom_domain = true }
]

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "DISCORD_DATA"
id = "7d6d9fbfdc3e4677b426a262f05c7a6f"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
