name: "CI/CD"

on:
    push:
      branches:
        - main
    pull_request:
      branches: [ main ]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v4
  #       with:
  #         version: 8
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'pnpm'
  #     - name: Install dependencies
  #       run: pnpm install

  #     - run: pnpm run lint
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [22]
    # needs: [lint]
    environment:
      name: 'production'
      url: 'https://vuwtechbot.workers.deez.ing/'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
